import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex min-h-screen bg-gray-500 justify-center items-center'>
        <div className='w-3/5 h-3/4 bg-white lg:grid-cols-2'>
          <div>
            <h1 className="text-5xl font-bold">
              Hello world!
            </h1>
          </div>
          <div className='right flex flex-col justify-evenly'>
            <h1 className=" text-5xl font-bold">
              Image
            </h1>
          </div>
        </div>
      </div>

    </div>
  )
}
